# Generated by Django 4.0.2 on 2022-02-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_time', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
                ('image_with_detection_obj', models.ImageField(upload_to='detection_img/%Y/%m/%d/', verbose_name='Изображение с распознанными объектами')),
                ('list_detection', models.TextField(blank=True, verbose_name='Список распознанных объектов')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-loading_time'],
            },
        ),
    ]
